spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: WARN
    com.afperdomo.bodegatech: INFO

server:
  port: ${SERVER_PORT:8080}